### PR TITLE
add a custom starfield effect

### LINKED ISSUE #10: can't build on linux
when i run `dotnet build`:
```
/usr/share/dotnet/sdk/6.0.101/Microsoft.Common.CurrentVersion.targets(1217,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.5.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/microlith57/.local/share/Steam/steamapps/common/Celeste/Mods/MaxHelpingHand/MaxHelpingHand.csproj]
    0 Warning(s)
    1 Error(s)
```
but .NET framework 4.5.2 isn't available for linux to my knowledge. other mods have had this and have fixed it (eg. snowberry) but i'm not sure how off the top of my head

### PR DESCRIPTION
**Pull request by microlith57**
it has custom sprites, colours, and alpha values, and you can have these be allocated in two different ways:
- shuffled, where each star gets a random sprite, colour, and alpha independently;
- not shuffled, where the first star gets the first (sprite, colour, alpha) triple, the second gets the second, and so on, repeating from the start when we run out

also fixes #10

### CODE REVIEW

**Comment by microlith57** [comment]
please make sure to test this; i'm not absolutely sure it works

**Comment by microlith57** [comment]
just noticed the `MMHOOK_Celeste.dll` sitting in the root directory. you can delete that i think

**Comment by microlith57** [comment]
actually i might want to change the non-shuffled behaviour of the starfield before you merge this

**Comment by microlith57** [comment]
done!

**Comment by max4805** [comment]
Thanks :+1:

**Pull request merged**
